Add CodeQL
pipeline-foundation/winmerge pull request #1
Opened 2021-04-23 06:38 UTC by szlatkow

2021-04-23 06:59 UTC, aleks-ivanov requested changes

2021-04-23 06:59 UTC, aleks-ivanov commented on .github/workflows/codeql-analysis.yml
> +        #   queries: security-and-quality
Why leave this code commented ?

2021-04-23 06:59 UTC, aleks-ivanov commented on .github/workflows/codeql-analysis.yml
> +          key: WinMergeDownloadDeps
1. Why is this step required for the CQL pipeline ?
2. The name is not good enough.
3. What is "chache" ?

2021-04-23 06:59 UTC, aleks-ivanov commented on .github/workflows/codeql-analysis.yml
> +          .\BuildAll.vs2019.cmd x64 -ci
Name and ID are not good enough. Should've checked out the names and IDs of the other steps, to use them as examples.

2021-04-23 06:59 UTC, aleks-ivanov commented on .github/workflows/codeql-analysis.yml
> +    name: CodeQL Analysis
Change the name of the job from "CodeQL Analysis" to "Analyze".
Change it in your template as well and I will in mine, too.

2021-04-23 07:32 UTC, szlatkow commented on .github/workflows/codeql-analysis.yml
> +          key: WinMergeDownloadDeps
actions/cache action allows caching dependencies and build outputs to improve workflow execution time.

2021-04-23 07:33 UTC, szlatkow commented on .github/workflows/codeql-analysis.yml
> +    name: CodeQL Analysis
Okay

2021-04-23 09:32 UTC, aleks-ivanov requested changes

2021-04-23 09:32 UTC, aleks-ivanov commented on .github/workflows/codeql-analysis.yml
> +    runs-on: windows-latest
Why windows not ubuntu ?

2021-04-28 07:28 UTC, szlatkow commented on .github/workflows/codeql-analysis.yml
> +        #   queries: security-and-quality
I was working on the building process and by mistake i left it commented.

2021-04-28 07:29 UTC, szlatkow commented on .github/workflows/codeql-analysis.yml
> +    runs-on: windows-latest
Changed the build platform to ubuntu.
Resolved the last requested changes.

2021-04-28 08:49 UTC, aleks-ivanov approved these changes

2021-04-28 08:49 UTC, aleks-ivanov commented on .github/workflows/codeql-analysis.yml
> +    runs-on: windows-latest
Alright

2021-04-28 08:52 UTC, merged